apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-r2kp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-r2kp
    app.kubernetes.io/part-of: integ-app-ibqr
  name: hacbs-test-project-r2kp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-r2kp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-r2kp
    spec:
      containers:
      - image: quay.io/rycole-appstudio/integration1-ieuh-tenant/integ-app-ibqr/hacbs-test-project-r2kp@sha256:28285b26b23a255b7a0b7b0514e444abf9b3c318059d428f1f739111165ed3d9
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
